@ECHO OFF
dotnet restore RabbitMQ.Core.sln
dotnet run -p .\Apigen\Apigen.csproj --apiName:AMQP_0_9_1 .\Docs\specs\amqp0-9-1.stripped.xml .\RabbitMQ.Client\autogenerated-api-0-9-1.cs
msbuild.\RabbitMQ.Client
dotnet build .\Unit
