@ECHO OFF
dotnet restore RabbitMQ.Core.Client.6.0.0.sln
dotnet run -p .\v6.0.0\Apigen\Apigen.csproj --apiName:AMQP_0_9_1 .\v5.1.2\Docs\specs\amqp0-9-1.stripped.xml .\v5.1.2\RabbitMQ.Client\autogenerated-api-0-9-1.cs --framework netcoreapp3.1
dotnet build .\v6.0.0\RabbitMQ.Client --configuration Release --framework netcoreapp3.1
dotnet build .\v6.0.0\Unit --framework netcoreapp3.1
